services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@auth-db:5432/auth_db
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - auth-db

  auth-db:
    image: postgres:14
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db

volumes:
  auth-db-data: